name: Next.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 21]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        run: npm install -g pnpm
          
      - name: Install dependencies
        run: |
          pnpm install

      - name: Run build
        run: |
          pnpm run build
